include: package:pedantic/analysis_options.yaml

linter:
  rules:
    - camel_case_types
    - constant_identifier_names
    - file_names
    - non_constant_identifier_names
    - package_names
    - package_prefixed_library_names